import { BarChart3, ChevronLeft, ChevronRight, Compass, LayoutDashboard, LogOut, ShieldAlert, UserRound } from "lucide-react";
import { Link, useLocation } from "react-router-dom";
import { useAppState } from "../context/AppStateContext";
import { learnerProfileComplete } from "../utils/profile";

export default function Sidebar({ collapsed, onToggle }: { collapsed: boolean; onToggle: () => void }) {
  const location = useLocation(); const { auth, state, logout } = useAppState();
  const complete = learnerProfileComplete(state?.learner_profile ?? null);
  const links = !complete ? [{ to: "/profile?required=1", label: "Complete profile", icon: ShieldAlert }] : [
    ...(state?.roadmap ? [{ to: "/app", label: "My path", icon: LayoutDashboard }] : []),
    { to: "/profile", label: "Profile", icon: UserRound },
    ...(state?.roadmap ? [{ to: "/analytics", label: "Progress", icon: BarChart3 }] : []),
  ];
  const progress = state?.roadmap?.nodes.length ? Math.round(state.roadmap.nodes.filter((node) => node.status === "complete").length / state.roadmap.nodes.length * 100) : 0;
  const active = (to: string) => to.startsWith("/app") ? location.pathname === "/app" || location.pathname.startsWith("/topic/") : location.pathname === to.split("?")[0];
  return <>
    <aside className={`fixed inset-y-0 left-0 z-40 hidden border-r border-emerald-950/10 bg-[#fffdf7]/80 shadow-[10px_0_34px_rgba(18,66,43,0.05)] backdrop-blur-xl transition-[width] duration-300 lg:flex lg:flex-col ${collapsed ? "w-[4.75rem]" : "w-64"}`}>
      <div className={`flex items-center border-b border-emerald-950/8 ${collapsed ? "justify-center p-3" : "gap-3 p-5"}`}><Link to="/app" className="group grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-emerald-800 text-amber-50 shadow-sm transition group-hover:-rotate-6"><Compass className="h-5 w-5" /></Link>{!collapsed && <Link to="/app" className="min-w-0 flex-1 text-lg font-semibold tracking-[-0.04em] text-emerald-950">LearnPath</Link>}<button onClick={onToggle} className={`grid h-8 w-8 place-items-center rounded-lg text-emerald-950/45 transition hover:bg-emerald-900/8 hover:text-emerald-900 ${collapsed ? "absolute -right-3 top-5 border border-emerald-950/10 bg-amber-50" : ""}`} aria-label={collapsed ? "Expand navigation" : "Collapse navigation"}>{collapsed ? <ChevronRight className="h-4 w-4" /> : <ChevronLeft className="h-4 w-4" />}</button></div>
      <nav aria-label="Primary" className="flex-1 space-y-1 p-3">{links.map(({ to, label, icon: Icon }) => <Link key={to} to={to} title={collapsed ? label : undefined} aria-current={active(to) ? "page" : undefined} className={`group flex items-center rounded-xl text-sm font-semibold transition ${collapsed ? "justify-center p-3" : "gap-3 px-3 py-3"} ${active(to) ? "bg-emerald-800 text-amber-50 shadow-sm" : "text-emerald-950/62 hover:bg-emerald-900/7 hover:text-emerald-900"}`}><Icon className="h-5 w-5 shrink-0" />{!collapsed && <span>{label}</span>}</Link>)}</nav>
      {!collapsed && state?.roadmap && <div className="mx-3 mb-3 rounded-2xl bg-emerald-100/70 p-3.5"><div className="flex justify-between text-xs font-semibold text-emerald-900"><span>Learning progress</span><span>{progress}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-emerald-950/10"><div className="h-full rounded-full bg-emerald-700 transition-all duration-700" style={{ width: `${progress}%` }} /></div></div>}
      <div className="border-t border-emerald-950/8 p-3"><div className={`mb-2 flex items-center ${collapsed ? "justify-center" : "gap-3 px-2"}`}><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-emerald-100 text-xs font-bold text-emerald-800">{auth?.username?.charAt(0).toUpperCase() ?? "G"}</span>{!collapsed && <span className="truncate text-sm font-semibold text-emerald-950">{auth?.username ?? "Guest"}</span>}</div><button onClick={logout} title={collapsed ? "Log out" : undefined} className={`flex w-full items-center rounded-xl py-2.5 text-sm font-semibold text-emerald-950/55 transition hover:bg-red-50 hover:text-red-700 ${collapsed ? "justify-center" : "gap-3 px-2"}`}><LogOut className="h-4 w-4" />{!collapsed && "Log out"}</button></div>
    </aside>
    <nav aria-label="Mobile navigation" className="fixed inset-x-3 bottom-3 z-40 flex items-center justify-around rounded-2xl border border-emerald-950/10 bg-[#fffdf7]/90 p-2 shadow-[0_12px_34px_rgba(18,66,43,0.16)] backdrop-blur-xl lg:hidden">{links.map(({ to, label, icon: Icon }) => <Link key={to} to={to} aria-current={active(to) ? "page" : undefined} className={`grid min-w-14 place-items-center gap-1 rounded-xl px-2 py-1.5 text-[10px] font-semibold ${active(to) ? "bg-emerald-800 text-amber-50" : "text-emerald-950/55"}`}><Icon className="h-4 w-4" /><span>{label}</span></Link>)}<button onClick={logout} className="grid min-w-14 place-items-center gap-1 rounded-xl px-2 py-1.5 text-[10px] font-semibold text-emerald-950/55"><LogOut className="h-4 w-4" /><span>Log out</span></button></nav>
  </>;
}
