import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ArrowRight, Eye, EyeOff, LockKeyhole, Loader2, UserRound } from "lucide-react";
import { createGuestSession, getState, login as apiLogin } from "../../api";
import { AuthField, AuthShell } from "../../components/auth/AuthShell";
import { useAppState } from "../../context/AppStateContext";
import { routeForStage } from "../../routing";

export default function Login() {
  const navigate = useNavigate(); const { login: setLogin } = useAppState();
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [visible, setVisible] = useState(false);
  const [busy, setBusy] = useState(false); const [guestBusy, setGuestBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!username.trim() || !password) return; setBusy(true); setError(null); try { const auth = await apiLogin(username, password); setLogin(auth); const { state } = await getState(auth.session_id); navigate(routeForStage(state.stage)); } catch { setError("We couldn’t sign you in. Check your username and password, then try again."); } finally { setBusy(false); } }
  async function guest() { setGuestBusy(true); setError(null); try { const response = await createGuestSession(); setLogin({ user_id: null, username: null, session_id: response.session_id }); navigate(routeForStage(response.state.stage)); } catch { setError("We couldn’t create a guest session. Please try again."); } finally { setGuestBusy(false); } }
  return <AuthShell eyebrow="Welcome back" title="Continue with intention." description="Pick up exactly where you left off with your learning path." error={error} onGuest={guest} guestBusy={guestBusy} formBusy={busy} footer={<><span>New to LearnPath? </span><Link to="/signup" className="font-semibold text-emerald-800 underline-offset-4 hover:underline">Create an account</Link></>} form={<form onSubmit={submit} className="space-y-5"><AuthField label="Username" icon={<UserRound className="h-4 w-4" aria-hidden="true" />}><input required value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" placeholder="Enter your username" className="h-12 w-full rounded-2xl border border-emerald-950/15 bg-white/60 py-3 pl-11 pr-4 text-sm text-emerald-950 outline-none transition placeholder:text-emerald-950/38 focus:border-emerald-700/40 focus:bg-white focus:ring-4 focus:ring-emerald-700/10" /></AuthField><AuthField label="Password" icon={<LockKeyhole className="h-4 w-4" aria-hidden="true" />}><input required value={password} onChange={(event) => setPassword(event.target.value)} type={visible ? "text" : "password"} autoComplete="current-password" placeholder="Enter your password" className="h-12 w-full rounded-2xl border border-emerald-950/15 bg-white/60 py-3 pl-11 pr-12 text-sm text-emerald-950 outline-none transition placeholder:text-emerald-950/38 focus:border-emerald-700/40 focus:bg-white focus:ring-4 focus:ring-emerald-700/10" /><button type="button" onClick={() => setVisible((value) => !value)} aria-label={visible ? "Hide password" : "Show password"} className="absolute inset-y-0 right-0 px-4 text-emerald-900/48 transition hover:text-emerald-800">{visible ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button></AuthField><button type="submit" disabled={busy || guestBusy || !username.trim() || !password} className="group flex w-full items-center justify-center gap-2 rounded-2xl bg-emerald-800 px-5 py-3.5 text-sm font-semibold text-amber-50 shadow-[0_12px_26px_rgba(13,89,55,0.22)] transition hover:-translate-y-0.5 hover:bg-emerald-900 disabled:pointer-events-none disabled:opacity-50">{busy ? <><Loader2 className="h-4 w-4 animate-spin" /> Signing in…</> : <>Sign in <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></>}</button></form>} />;
}
